### ISSUE TITLE
Add keyboard navigation

### ISSUE THREAD

**Issue by Agusum** [HamedMP/SuperTabs#1]
As a user I would like to use the arrow keys and the return key to navigate through the list of tabs presented by the extension and open the one I'm interested in.

**Comment by HamedMP** [comment]
Hi @Agusum, Thank you so much for giving feedback, keyboard navigation is really a cool idea that we are working on it and will release it soon. Stay tuned!

**Comment by HamedMP** [comment]
Hi again @Agusum 
In the latest release, you can use Tab for navigation. For a demo look [here](https://www.youtube.com/watch?v=uad9mZknUDk)

**Comment by Agusum** [comment]
Thanks for adding this! Will it be possible to also add the ability to navigate using the arrow keys? I find it more intuitive than using Tab or Shift+Tab.
